CREATE TABLE task_tracker (
   id INT AUTO_INCREMENT PRIMARY KEY,
    task_manager_id INT NOT NULL,
    start_date VARCHAR(255) NOT NULL,
    end_date TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (task_manager_id) REFERENCES TaskManager(id) ON DELETE CASCADE ON UPDATE CASCADE
);